// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVVMtFWMVVzzxM8u1VCLFcddOC03zK_Zg',
    appId: '1:328834457993:web:dff3124c9add04bbe5c158',
    messagingSenderId: '328834457993',
    projectId: 'flutter-velog-sample',
    authDomain: 'flutter-velog-sample.firebaseapp.com',
    storageBucket: 'flutter-velog-sample.appspot.com',
    measurementId: 'G-THD1EJ4R0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEaM2n88U3jUopkIGAr-qLbnPV2XIkok',
    appId: '1:328834457993:android:f0cc7e1f29cb08cce5c158',
    messagingSenderId: '328834457993',
    projectId: 'flutter-velog-sample',
    storageBucket: 'flutter-velog-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuK-k2RaeBCl1QZ7iIU7AsD5SeoUl0_hM',
    appId: '1:328834457993:ios:c978cf923953818ce5c158',
    messagingSenderId: '328834457993',
    projectId: 'flutter-velog-sample',
    storageBucket: 'flutter-velog-sample.appspot.com',
    iosClientId:
        '328834457993-7e2rdf8e3gbnh938oak7i7okdbr76cq3.apps.googleusercontent.com',
    iosBundleId: 'com.tyger.velogsample',
  );
}
